import {
  ApiOutline,
  AppstoreOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  BarChartOutline,
  BellOutline,
  CalendarOutline,
  CheckCircleFill,
  CheckCircleOutline,
  CheckOutline,
  ClockCircleOutline,
  CloseCircleFill,
  CloseOutline,
  CloudUploadOutline,
  CopyOutline,
  DashboardOutline,
  DeleteOutline,
  DownloadOutline,
  DownOutline,
  EditOutline,
  ExclamationCircleFill,
  EyeInvisibleOutline,
  EyeOutline,
  FileExcelOutline,
  FileTextOutline,
  FilterOutline,
  GlobalOutline,
  InboxOutline,
  InfoCircleOutline,
  LockOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuOutline,
  MenuUnfoldOutline,
  MoreOutline,
  PhoneOutline,
  PictureOutline,
  PlusOutline,
  QuestionCircleOutline,
  ReloadOutline,
  RightOutline,
  SafetyOutline,
  SaveOutline,
  SearchOutline,
  SendOutline,
  SettingOutline,
  ShoppingCartOutline,
  TeamOutline,
  ThunderboltOutline,
  UserAddOutline,
  UserOutline,
  WalletOutline,
  WarningOutline,
} from '@ant-design/icons-angular/icons';

export const APP_ICONS = [
  ApiOutline, AppstoreOutline, ArrowDownOutline, ArrowLeftOutline, ArrowRightOutline, ArrowUpOutline, BarChartOutline,
  BellOutline, CalendarOutline, CheckCircleFill, CheckCircleOutline, CheckOutline, ClockCircleOutline, CloseCircleFill,
  CloseOutline, CloudUploadOutline, CopyOutline, DashboardOutline, DeleteOutline, DownloadOutline, DownOutline, EditOutline,
  ExclamationCircleFill, EyeInvisibleOutline, EyeOutline, FileExcelOutline, FileTextOutline, FilterOutline, GlobalOutline,
  InboxOutline, InfoCircleOutline, LockOutline, LogoutOutline, MailOutline, MenuFoldOutline, MenuOutline, MenuUnfoldOutline,
  MoreOutline, PhoneOutline, PictureOutline, PlusOutline, QuestionCircleOutline, ReloadOutline, RightOutline, SafetyOutline,
  SaveOutline, SearchOutline, SendOutline, SettingOutline, ShoppingCartOutline, TeamOutline, ThunderboltOutline,
  UserAddOutline, UserOutline, WalletOutline, WarningOutline,
];
