import { Component, signal } from '@angular/core';
import { UiInputComponent, UiNumberComponent, UiTextareaComponent } from '@ui';
import { ApiRow, COMMON_CONTROL_API, DOC } from '../doc.components';

@Component({
  selector: 'section-text-inputs',
  standalone: true,
  imports: [...DOC, UiInputComponent, UiTextareaComponent, UiNumberComponent],
  template: `
    <doc-section anchor="input" heading="Input" selector="<ui-input>" intro="Single-line text. Handles email, password (with show/hide), phone, URL and search. Supports icons, inline text, addons, a clear button, a character counter and debounced output.">
      <doc-example heading="Sizes" description="sm 30 px for dense toolbars, md 38 px default, lg 46 px for sign-in and hero forms." [code]="code.sizes" grid>
        <ui-input size="sm" label="Small" placeholder="Small input" />
        <ui-input label="Medium (default)" placeholder="Medium input" />
        <ui-input size="lg" label="Large" placeholder="Large input" />
      </doc-example>

      <doc-example heading="Icons, inline text and addons" [code]="code.affix" grid>
        <ui-input label="Email" type="email" prefixIcon="mail" placeholder="you@company.vn" />
        <ui-input label="Website" prefix="https://" placeholder="harbor.vn" />
        <ui-input label="Phone" type="tel" addonBefore="+84" placeholder="912 345 678" />
        <ui-input label="Weight" suffix="kg" placeholder="0" inputmode="decimal" />
        <ui-input label="Domain" addonAfter=".harbor.vn" placeholder="workspace" />
        <ui-input label="Location" suffixIcon="environment" placeholder="Hà Nội" />
      </doc-example>

      <doc-example heading="Password, clear button and counter" [code]="code.features" grid>
        <ui-input label="Password" type="password" prefixIcon="lock" placeholder="At least 8 characters" />
        <ui-input label="Clearable" [(value)]="clearDemo" clearable />
        <ui-input label="Display name" [maxChars]="30" showCount [(value)]="countDemo" hint="Shown on your public profile" />
      </doc-example>

      <doc-example heading="States" description="Disabled, read-only, hint, tooltip and an error passed in without a form." [code]="code.states" grid>
        <ui-input label="Disabled" value="Locked by admin" disabled />
        <ui-input label="Read-only" value="EMP-00421" readonly hint="Generated by the system" />
        <ui-input label="With tooltip" tooltip="We use this to send invoices." placeholder="billing@company.vn" />
        <ui-input label="Error (standalone)" value="an.nguyen@" error="Enter a valid email address" />
      </doc-example>

      <doc-example heading="Horizontal layout" description="Label in a left column; stacks back to vertical under 640 px." [code]="code.horizontal" stack>
        <ui-input layout="horizontal" label="Company name" placeholder="Công ty TNHH Harbor" />
        <ui-input layout="horizontal" label="Tax code" placeholder="0101234567" hint="10 or 13 digits" />
      </doc-example>

      <doc-example heading="Search with debounce" description="Typing updates [(value)] instantly; (debounced) fires 400 ms after the last keystroke, which is what you send to the API." [code]="code.search" stack>
        <ui-input type="search" prefixIcon="search" placeholder="Search people" clearable [debounce]="400" [(value)]="search" (debounced)="searched.set($event)" />
        <div class="out">value: <code>{{ search() || '∅' }}</code> · debounced: <code>{{ searched() || '∅' }}</code></div>
      </doc-example>

      <doc-api heading="ui-input properties" [rows]="inputApi" />
    </doc-section>

    <doc-section anchor="textarea" heading="Textarea" selector="<ui-textarea>" intro="Multi-line text that grows with its content between minRows and maxRows.">
      <doc-example heading="Autosize, counter and error" [code]="code.textarea" grid>
        <ui-textarea label="Notes" placeholder="Anything the team should know" />
        <ui-textarea label="Bio" [maxChars]="160" showCount [minRows]="3" [(value)]="bio" />
        <ui-textarea label="Reason" error="Tell us why you are cancelling" [minRows]="2" />
      </doc-example>
      <doc-api heading="ui-textarea properties" [rows]="textareaApi" />
    </doc-section>

    <doc-section anchor="number" heading="Number" selector="<ui-number>" intro="Numeric entry with stepper, bounds and display formatting. The value stays a plain number; formatting is display only.">
      <doc-example heading="Formats" [code]="code.number" grid>
        <ui-number label="Quantity" [min]="1" [max]="99" [(value)]="qty" hint="1–99" />
        <ui-number label="Price" format="currency" currency="₫" [step]="1000" [(value)]="price" />
        <ui-number label="Discount" format="percent" [min]="0" [max]="100" [(value)]="discount" />
        <ui-number label="Weight" unit="kg" [precision]="1" [step]="0.5" [(value)]="weight" />
        <ui-number label="Headcount" format="thousands" [(value)]="headcount" />
        <ui-number label="Disabled" [value]="42" disabled />
      </doc-example>
      <div class="out">price = <code>{{ price() }}</code> (number), discount = <code>{{ discount() }}</code></div>
      <doc-api heading="ui-number properties" [rows]="numberApi" />
    </doc-section>
  `,
  styles: [`.out { font-size: 12.5px; color: var(--text-3); } code { font-family: 'JetBrains Mono', monospace; color: var(--text); }`],
})
export class TextInputsSectionComponent {
  clearDemo = signal('Clear me');
  countDemo = signal('Harbor team');
  search = signal('');
  searched = signal('');
  bio = signal('Product designer in Đà Nẵng.');
  qty = signal<number | null>(3);
  price = signal<number | null>(1250000);
  discount = signal<number | null>(15);
  weight = signal<number | null>(2.5);
  headcount = signal<number | null>(12480);

  readonly inputApi: ApiRow[] = [
    { name: 'type', type: "'text' | 'email' | 'password' | 'tel' | 'url' | 'search'", default: "'text'", description: 'Password adds a show/hide button.' },
    { name: 'prefixIcon / suffixIcon', type: 'string', description: 'Ant icon name inside the box.' },
    { name: 'prefix / suffix', type: 'string', description: 'Short text inside the box, e.g. "https://", "kg".' },
    { name: 'addonBefore / addonAfter', type: 'string', description: 'Grey attached box outside the input, e.g. "+84".' },
    { name: 'clearable', type: 'boolean', default: 'false', description: 'Show a clear button when there is a value.' },
    { name: 'maxChars / showCount', type: 'number / boolean', description: 'Limit length and show "12/30".' },
    { name: 'debounce', type: 'number (ms)', default: '0', description: 'Delay for (debounced). 0 disables it.' },
    { name: '(debounced)', type: 'string', description: 'Value after the user stops typing.' },
    { name: '(enter)', type: 'string', description: 'Enter key pressed.' },
    { name: 'autocomplete / inputmode', type: 'string', description: 'Passed to the native input.' },
    ...COMMON_CONTROL_API,
  ];

  readonly textareaApi: ApiRow[] = [
    { name: 'minRows / maxRows', type: 'number', default: '3 / 8', description: 'Autosize bounds.' },
    { name: 'maxChars / showCount', type: 'number / boolean', description: 'Limit and counter in the corner.' },
  ];

  readonly numberApi: ApiRow[] = [
    { name: 'format', type: "'plain' | 'thousands' | 'currency' | 'percent'", default: "'plain'", description: 'Display formatting; value is always a number.' },
    { name: 'currency', type: 'string', default: "'₫'", description: 'Suffix when format="currency".' },
    { name: 'unit', type: 'string', description: 'Suffix text such as "kg".' },
    { name: 'min / max / step', type: 'number', description: 'Bounds and stepper increment.' },
    { name: 'precision', type: 'number', description: 'Decimal places (0 for currency and thousands by default).' },
    { name: 'locale', type: 'string', default: "'en-US'", description: 'Grouping separator for formatting.' },
  ];

  readonly code = {
    sizes: `<ui-input size="sm" label="Small" />
<ui-input label="Medium (default)" />
<ui-input size="lg" label="Large" />`,
    affix: `<ui-input label="Email" type="email" prefixIcon="mail" />
<ui-input label="Website" prefix="https://" />
<ui-input label="Phone" type="tel" addonBefore="+84" />
<ui-input label="Weight" suffix="kg" inputmode="decimal" />
<ui-input label="Domain" addonAfter=".harbor.vn" />`,
    features: `<ui-input label="Password" type="password" prefixIcon="lock" />
<ui-input label="Clearable" [(value)]="text" clearable />
<ui-input label="Display name" [maxChars]="30" showCount hint="Shown on your public profile" />`,
    states: `<ui-input label="Disabled" value="Locked by admin" disabled />
<ui-input label="Read-only" value="EMP-00421" readonly />
<ui-input label="With tooltip" tooltip="We use this to send invoices." />
<ui-input label="Error" error="Enter a valid email address" />

<!-- Inside a form you don't pass error: it comes from the validators -->
<ui-input formControlName="email" label="Email" />`,
    horizontal: `<ui-input layout="horizontal" label="Company name" />
<ui-input layout="horizontal" labelWidth="200px" label="Tax code" hint="10 or 13 digits" />`,
    search: `<ui-input
  type="search" prefixIcon="search" clearable
  [(value)]="search"
  [debounce]="400"
  (debounced)="load($event)" />`,
    textarea: `<ui-textarea label="Notes" />
<ui-textarea label="Bio" [maxChars]="160" showCount [minRows]="3" />
<ui-textarea formControlName="reason" label="Reason" [minRows]="2" />`,
    number: `<ui-number label="Quantity" [min]="1" [max]="99" />
<ui-number label="Price" format="currency" currency="₫" [step]="1000" />
<ui-number label="Discount" format="percent" [min]="0" [max]="100" />
<ui-number label="Weight" unit="kg" [precision]="1" [step]="0.5" />
<ui-number formControlName="headcount" label="Headcount" format="thousands" />`,
  };
}
